const teams = {
  ARG: { country: 'ARG', name: 'Argentina' },
  FRA: { country: 'FRA', name: 'France' },
  BRA: { country: 'BRA', name: 'Brazil' },
  ENG: { country: 'ENG', name: 'England' },
  BEL: { country: 'BEL', name: 'Belgium' },
  CRO: { country: 'CRO', name: 'Croatia' },
  NED: { country: 'NED', name: 'Netherlands' },
  ITA: { country: 'ITA', name: 'Italy' },
  POR: { country: 'POR', name: 'Portugal' },
  ESP: { country: 'ESP', name: 'Spain' },
  USA: { country: 'USA', name: 'USA' },
  MEX: { country: 'MEX', name: 'Mexico' },
  SUI: { country: 'SUI', name: 'Switzerland' },
  MAR: { country: 'MAR', name: 'Morocco' },
  GER: { country: 'GER', name: 'Germany' },
  URU: { country: 'URU', name: 'Uruguay' },
  COL: { country: 'COL', name: 'Colombia' },
  SEN: { country: 'SEN', name: 'Senegal' },
  DEN: { country: 'DEN', name: 'Denmark' },
  JPN: { country: 'JPN', name: 'Japan' },
  PER: { country: 'PER', name: 'Peru' },
  IRN: { country: 'IRN', name: 'IR Iran' },
  SWE: { country: 'SWE', name: 'Sweden' },
  UKR: { country: 'UKR', name: 'Ukraine' },
  SRB: { country: 'SRB', name: 'Serbia' },
  POL: { country: 'POL', name: 'Poland' },
  AUS: { country: 'AUS', name: 'Australia' },
  KOR: { country: 'KOR', name: 'Korea Republic' },
  AUT: { country: 'AUT', name: 'Austria' },
  SCO: { country: 'SCO', name: 'Scotland' },
  TUN: { country: 'TUN', name: 'Tunisia' },
  CHI: { country: 'CHI', name: 'Chile' },
  ALG: { country: 'ALG', name: 'Algeria' },
  EGY: { country: 'EGY', name: 'Egypt' },
  WAL: { country: 'WAL', name: 'Wales' },
  HUN: { country: 'HUN', name: 'Hungary' },
  CZE: { country: 'CZE', name: 'Czechia' },
  RUS: { country: 'RUS', name: 'Russia' },
  ECU: { country: 'ECU', name: 'Ecuador' },
  NGA: { country: 'NGA', name: 'Nigeria' },
  TUR: { country: 'TUR', name: 'Türkiye' },
  CMR: { country: 'CMR', name: 'Cameroon' },
  CAN: { country: 'CAN', name: 'Canada' },
  NOR: { country: 'NOR', name: 'Norway' },
  PAN: { country: 'PAN', name: 'Panama' },
  CRC: { country: 'CRC', name: 'Costa Rica' },
  SVK: { country: 'SVK', name: 'Slovakia' },
  ROU: { country: 'ROU', name: 'Romania' },
  PAR: { country: 'PAR', name: 'Paraguay' },
  GRE: { country: 'GRE', name: 'Greece' },
  MLI: { country: 'MLI', name: 'Mali' },
  CIV: { country: 'CIV', name: "Côte d'Ivoire" },
  IRL: { country: 'IRL', name: 'Republic of Ireland' },
  KSA: { country: 'KSA', name: 'Saudi Arabia' },
  FIN: { country: 'FIN', name: 'Finland' },
  BFA: { country: 'BFA', name: 'Burkina Faso' },
  VEN: { country: 'VEN', name: 'Venezuela' },
  JAM: { country: 'JAM', name: 'Jamaica' },
  QAT: { country: 'QAT', name: 'Qatar' },
  GHA: { country: 'GHA', name: 'Ghana' },
  SVN: { country: 'SVN', name: 'Slovenia' },
  BIH: { country: 'BIH', name: 'Bosnia and Herzegovina' },
  RSA: { country: 'RSA', name: 'South Africa' },
  NIR: { country: 'NIR', name: 'Northern Ireland' },
  ALB: { country: 'ALB', name: 'Albania' },
  CPV: { country: 'CPV', name: 'Cabo Verde' },
  ISL: { country: 'ISL', name: 'Iceland' },
  MKD: { country: 'MKD', name: 'North Macedonia' },
  COD: { country: 'COD', name: 'Congo DR' },
  IRQ: { country: 'IRQ', name: 'Iraq' },
  MNE: { country: 'MNE', name: 'Montenegro' },
  UAE: { country: 'UAE', name: 'United Arab Emirates' },
  OMA: { country: 'OMA', name: 'Oman' },
  UZB: { country: 'UZB', name: 'Uzbekistan' },
  SLV: { country: 'SLV', name: 'El Salvador' },
  ISR: { country: 'ISR', name: 'Israel' },
  BUL: { country: 'BUL', name: 'Bulgaria' },
  GEO: { country: 'GEO', name: 'Georgia' },
  HON: { country: 'HON', name: 'Honduras' },
  CHN: { country: 'CHN', name: 'China PR' },
  GUI: { country: 'GUI', name: 'Guinea' },
  JOR: { country: 'JOR', name: 'Jordan' },
  BOL: { country: 'BOL', name: 'Bolivia' },
  ZAM: { country: 'ZAM', name: 'Zambia' },
  GAB: { country: 'GAB', name: 'Gabon' },
  BHR: { country: 'BHR', name: 'Bahrain' },
  HAI: { country: 'HAI', name: 'Haiti' },
  CUW: { country: 'CUW', name: 'Curaçao' },
  LUX: { country: 'LUX', name: 'Luxembourg' },
  ARM: { country: 'ARM', name: 'Armenia' },
  EQG: { country: 'EQG', name: 'Equatorial Guinea' },
  UGA: { country: 'UGA', name: 'Uganda' },
  BEN: { country: 'BEN', name: 'Benin' },
  SYR: { country: 'SYR', name: 'Syria' },
  VIE: { country: 'VIE', name: 'Vietnam' },
  PLE: { country: 'PLE', name: 'Palestine' },
  KGZ: { country: 'KGZ', name: 'Kyrgyz Republic' },
  BLR: { country: 'BLR', name: 'Belarus' },
  IND: { country: 'IND', name: 'India' },
  LBN: { country: 'LBN', name: 'Lebanon' },
  MTN: { country: 'MTN', name: 'Mauritania' },
  TRI: { country: 'TRI', name: 'Trinidad and Tobago' },
  NZL: { country: 'NZL', name: 'Aotearoa New Zealand' },
  KAZ: { country: 'KAZ', name: 'Kazakhstan' },
  KEN: { country: 'KEN', name: 'Kenya' },
  CGO: { country: 'CGO', name: 'Congo' },
  GUA: { country: 'GUA', name: 'Guatemala' },
  MAD: { country: 'MAD', name: 'Madagascar' },
  KVX: { country: 'KVX', name: 'Kosovo' },
  TJK: { country: 'TJK', name: 'Tajikistan' },
  EST: { country: 'EST', name: 'Estonia' },
  GNB: { country: 'GNB', name: 'Guinea-Bissau' },
  THA: { country: 'THA', name: 'Thailand' },
  NAM: { country: 'NAM', name: 'Namibia' },
  PRK: { country: 'PRK', name: 'Korea DPR' },
  ANG: { country: 'ANG', name: 'Angola' },
  MOZ: { country: 'MOZ', name: 'Mozambique' },
  CYP: { country: 'CYP', name: 'Cyprus' },
  GAM: { country: 'GAM', name: 'The Gambia' },
  SLE: { country: 'SLE', name: 'Sierra Leone' },
  AZE: { country: 'AZE', name: 'Azerbaijan' },
  TOG: { country: 'TOG', name: 'Togo' },
  MWI: { country: 'MWI', name: 'Malawi' },
  TAN: { country: 'TAN', name: 'Tanzania' },
  ZIM: { country: 'ZIM', name: 'Zimbabwe' },
  CTA: { country: 'CTA', name: 'Central African Republic' },
  LBY: { country: 'LBY', name: 'Libya' },
  NIG: { country: 'NIG', name: 'Niger' },
  FRO: { country: 'FRO', name: 'Faroe Islands' },
  COM: { country: 'COM', name: 'Comoros' },
  SDN: { country: 'SDN', name: 'Sudan' },
  ATG: { country: 'ATG', name: 'Antigua and Barbuda' },
  SOL: { country: 'SOL', name: 'Solomon Islands' },
  LVA: { country: 'LVA', name: 'Latvia' },
  PHI: { country: 'PHI', name: 'Philippines' },
  MAS: { country: 'MAS', name: 'Malaysia' },
  KUW: { country: 'KUW', name: 'Kuwait' },
  TKM: { country: 'TKM', name: 'Turkmenistan' },
  RWA: { country: 'RWA', name: 'Rwanda' },
  BDI: { country: 'BDI', name: 'Burundi' },
  NCA: { country: 'NCA', name: 'Nicaragua' },
  ETH: { country: 'ETH', name: 'Ethiopia' },
  SUR: { country: 'SUR', name: 'Suriname' },
  LTU: { country: 'LTU', name: 'Lithuania' },
  SKN: { country: 'SKN', name: 'St Kitts and Nevis' },
  SWZ: { country: 'SWZ', name: 'Eswatini' },
  BOT: { country: 'BOT', name: 'Botswana' },
  LBR: { country: 'LBR', name: 'Liberia' },
  HKG: { country: 'HKG', name: 'Hong Kong, China' },
  IDN: { country: 'IDN', name: 'Indonesia' },
  LES: { country: 'LES', name: 'Lesotho' },
  DOM: { country: 'DOM', name: 'Dominican Republic' },
  TPE: { country: 'TPE', name: 'Chinese Taipei' },
  AND: { country: 'AND', name: 'Andorra' },
  MDV: { country: 'MDV', name: 'Maldives' },
  YEM: { country: 'YEM', name: 'Yemen' },
  AFG: { country: 'AFG', name: 'Afghanistan' },
  SIN: { country: 'SIN', name: 'Singapore' },
  PNG: { country: 'PNG', name: 'Papua New Guinea' },
  MYA: { country: 'MYA', name: 'Myanmar' },
  NCL: { country: 'NCL', name: 'New Caledonia' },
  TAH: { country: 'TAH', name: 'Tahiti' },
  PUR: { country: 'PUR', name: 'Puerto Rico' },
  MDA: { country: 'MDA', name: 'Moldova' },
  VAN: { country: 'VAN', name: 'Vanuatu' },
  BRB: { country: 'BRB', name: 'Barbados' },
  SSD: { country: 'SSD', name: 'South Sudan' },
  GUY: { country: 'GUY', name: 'Guyana' },
  FIJ: { country: 'FIJ', name: 'Fiji' },
  LCA: { country: 'LCA', name: 'St Lucia' },
  MLT: { country: 'MLT', name: 'Malta' },
  CUB: { country: 'CUB', name: 'Cuba' },
  BER: { country: 'BER', name: 'Bermuda' },
  GRN: { country: 'GRN', name: 'Grenada' },
  NEP: { country: 'NEP', name: 'Nepal' },
  CAM: { country: 'CAM', name: 'Cambodia' },
  BLZ: { country: 'BLZ', name: 'Belize' },
  VIN: { country: 'VIN', name: 'St Vincent and the Grenadines' },
  MSR: { country: 'MSR', name: 'Montserrat' },
  MRI: { country: 'MRI', name: 'Mauritius' },
  CHA: { country: 'CHA', name: 'Chad' },
  MAC: { country: 'MAC', name: 'Macau' },
  MNG: { country: 'MNG', name: 'Mongolia' },
  DMA: { country: 'DMA', name: 'Dominica' },
  BHU: { country: 'BHU', name: 'Bhutan' },
  STP: { country: 'STP', name: 'São Tomé and Príncipe' },
  LAO: { country: 'LAO', name: 'Laos' },
  COK: { country: 'COK', name: 'Cook Islands' },
  BAN: { country: 'BAN', name: 'Bangladesh' },
  BRU: { country: 'BRU', name: 'Brunei Darussalam' },
  DJI: { country: 'DJI', name: 'Djibouti' },
  TLS: { country: 'TLS', name: 'Timor-Leste' },
  CAY: { country: 'CAY', name: 'Cayman Islands' },
  SEY: { country: 'SEY', name: 'Seychelles' },
  ERI: { country: 'ERI', name: 'Eritrea' },
  SOM: { country: 'SOM', name: 'Somalia' },
  BAH: { country: 'BAH', name: 'Bahamas' },
  GIB: { country: 'GIB', name: 'Gibraltar' },
  ARU: { country: 'ARU', name: 'Aruba' },
  LIE: { country: 'LIE', name: 'Liechtenstein' },
  PAK: { country: 'PAK', name: 'Pakistan' },
  TCA: { country: 'TCA', name: 'Turks and Caicos Islands' },
  GUM: { country: 'GUM', name: 'Guam' },
  SRI: { country: 'SRI', name: 'Sri Lanka' },
  VIR: { country: 'VIR', name: 'US Virgin Islands' },
  VGB: { country: 'VGB', name: 'British Virgin Islands' },
  AIA: { country: 'AIA', name: 'Anguilla' },
  SMR: { country: 'SMR', name: 'San Marino' },
  ASA: { country: 'ASA', name: 'American Samoa' },
  SAM: { country: 'SAM', name: 'Samoa' },
  TGA: { country: 'TGA', name: 'Tonga' },
};

export default teams;
